Repository f-lab-edu/sool-dam-a, pull requests merged in 2022-10, with the labels that each got.

#37 [#2] github actions를 이용한 ci 구축
  .github/workflows/build-on-pr.yml
Labels: feature, effort : 2

#39 [#38] Jacoco 연동하기
  build.gradle
Labels: feature, effort : 1

#41 [#40] SpringBoot, Mybatis, MySQL 연동, 폴더 구조 세팅
  build.gradle
  lombok.config
  src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
  src/main/java/com/flab/sooldama/domain/user/dao/UserMapper.java
  src/main/java/com/flab/sooldama/domain/user/domain/User.java
  src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
  src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
  src/main/java/com/flab/sooldama/domain/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/UserMapper.xml
  src/test/java/com/flab/sooldama/SoolDamAApplicationTests.java
  src/test/java/com/flab/sooldama/domain/user/api/UserApiTest.java
Labels: feature, effort : 1

#44 [#43] Github Actions 추가 세팅
  .github/workflows/build-on-pr.yml
Labels: feature, effort : 2

#53 [#47] Github Actions 테스트 환경 세팅
  .github/workflows/build-on-pr.yml
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: bug, effort : 4

#57 [#55] PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, effort : 1
